import time

print("THIS GAME IN BETA")
print("THIS GAME CAN CONTAINS BUGS")
time.sleep(5)
print("Welcome to SchoolDay!")
input('Press enter to play.')
print("Day 1")
time.sleep(5)
print("Do you wanna go to school today?")
print("Yes or No")
quest1 = input('')
if quest1 == "yes":
  print("Good!")
  input('You see a beautiful girl...')
  input("She's name's Jessica...")
  quest2 = input('Do you wanna talk with her? ')
  if quest2 == "yes":
    input('You go to her to talk...')
    input("You say 'hi' to her")
    input('She says "no"')
    input('~WHAT THE HELL "NO" IS MEANS???~')
    input('You: Why no?')
    input('Jessica: cus u ugly asf')
    input('You really likes Jessica..')
    input('You: Bye!')
    input('Jessica: Bye, bye, ugly boy')
    print('Do you wanna go to GYM to be beautiful or rizz up Jessica?')
    quest3 = input('gym or rizz or kidnap? ')
    if quest3 == "gym":
      input('You going to GYM..')
      input('You decided to pump up your muscles and abs..')
      input('Day 50')
      input('Now you are the most handsome boy in the whole school and now Jessica is yours..')
      print("GYM Ending (good)")
      print("Now you got a girlfriend, yay!!")
      time.sleep(2)
      print("Now you not loser")
      time.sleep(0.9)
    elif quest3 == "rizz":
      input('You found rizz lessons on eBay..')
      input('You learned how to rizz..')
      input('You rizzed up Jessica..')
      print("Rizz Ending")
      print("yay gf")
      time.sleep(2)
      print("RIZZLER!!")
      time.sleep(0.9)
    elif quest3 == "kidnap":
      input('You kidnapped Jessica..')
      input('Jessica: WHAT THE HELL WRONG WITH YOU?!?')
      input("You put a gag in Jessica's mouth..")
      input('You put Jessica in the basement..')
      input('You torture Jessica every day..')
      input('But you got arrested by Police..')
      print("Kidnap Ending")
      print("Why you kidnapped Jessica, lil bro?")
      time.sleep(2)
      print("STILL NO GF???")
      time.sleep(0.9)
    else:
      input('Error')
  elif quest2 == "no":
    print("No girlfriend Ending")
    print("no gf?..")
    time.sleep(2)
    print("LOSER!!!")
    time.sleep(0.9)
  else:
    input('Error')
elif quest1 == "no":
  print("Bad Ending")
  print("You got grounded..")
  time.sleep(2)
  print("And you didn't get girlfriend...")
  time.sleep(5)
  print("LOSER!!!")
  time.sleep(0.9)
else:
  input('Error')
